gaiah:
  repo:
    create_repo: True
    repo_name: "AIRA-Sample00"
    description: ""
    private: false

  local:
    init_repo: True
    repo_dir: "C:/Prj/AIRA-Sample/AIRA-Sample00"
    no_initial_commit: false

  commit:
    process_commits: false
    commit_msg_path: ".Gaiah.md"
    branch_name: null